### DATABASE CONFIGURATION ###
DatabaseUsername: bgUser # Set the mysql database username
DatabasePassword: 123456 # Set the mysql database password
DatabaseHost: localhost # Set the mysql server host
DatabaseName: bgdb # Set the name of the database 

### MANAGEMENT API CONFIGURATION ###
ManagementAPIPort : 1698 # Set the port number used by the management api, should be the same across all bg divisions, eg. NES, ERS, STS
ManagementAPIHost: 127.0.0.1 # This defines the IP address of the unified management API server, default is 127.0.0.1

#### APACHE KAFKA CONFIGURATION ###
KafkaHost: 127.0.0.1 # Set the address of the server running the kafka broker, default is localhost
KafkaPort: 9092 # Set the port to connect to the kafka broker, default is 9092

#### SYSTEM TELEMETRY CONFIGURATION #
SystemTelemetryProducerEventPollingPeriod: 0.5 # Set the time that the system telemetry module is willing to wait for callback events

### ZOOKEEPER CONFIGURATION ###
ZookeeperHost: 10.1.18.1 # Set the host running the zookeeper server, default is localhost
ZookeeperPort: 2181 # Set port used to connect to the zookeeper server, default is 2181


### LOGGER CONFIGURATION ###
PrintLogText: True # Enable or Disable Printing Logs
SecondsToKeepLogs: 100000  # Define The Number Of Seconds To Keep Logs
ConsoleOutputEnabled: True # Enable or disable console output
ConsoleColorEnabled: True # Enable or disable console color output
DisplayLogLevelsAsText: False # Enable or disable showing log levels as text or numerical values

# Set The Colors For Various Log Levels #
LogLevelColors:
    0: [255,255,255] # System
    1: [77,166,255] # Config
    2: [179,255,217] # Audit
    3: [181,121,255] # Info
    4: [212,0,255] # Detail
    5: [106,255,77] # Fine
    6: [204,153,0] # Finer
    7: [149,179,0] # Finest
    8: [255,255,0] # Warning
    9: [255,170,0] # Severe (Non Fatal)
    10: [255,0,0] # Fatal

# Set Name For Log Strings #
LogLevelNames:
    0: System
    1: Config
    2: Audit
    3: Info
    4: Detail
    5: Fine
    6: Finer
    7: Finest
    8: Warning
    9: Severe
    10: Fatal
